# mkdocs.yml

# Project information
site_name: "Mike's Notes"
site_url: "https://mikemol.github.io"
site_author: Mike Mol
site_description: >-
  Mike Mol's blog. Discussing why's, how's and random technical musings.

# Repository information
repo_name: mikemol/mikemol.github.io
repo_url: "https://github.com/mikemol/mikemol.github.io"

# Theme Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes # This automatically creates the blog sidebar
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

# Social Links and Analytics
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/mikemol
    - icon: fontawesome/brands/github
      link: https://github.com/mikemol
  analytics:
    provider: google
    property: UA-112008517-1

# Markdown extensions
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true

# Plugins
plugins:
  - search
  - redirects:
      redirect_maps:
        '2020/06/14/on-github-actions-security-controls.md': 'blog/2020/06/14/on-github-actions-security-controls/index.md'
        '2018/01/05/here-i-go-again-with-a-blog.md': 'blog/2018/01/05/here-i-go-again-with-a-blog/index.md'
        '2018/01/05/blank-renders.md': 'blog/2018/01/05/blank-renders/index.md'
        '2018/01/12/graphviz-technique-nodes-as-edge-labels.md': 'blog/2018/01/12/graphviz-technique-nodes-as-edge-labels/index.md'
        '2018/01/06/ifttt-integration-test-f1edfb94-570f-48c3-98a7-8baf826205c4.md': 'blog/2018/01/06/ifttt-integration-test-f1edfb94-570f-48c3-98a7-8baf826205c4/index.md'
        '2018/01/07/graphviz-jekyll-js.md': 'blog/2018/01/07/graphviz-jekyll-js/index.md'
        '2018/01/09/blog-workflow.md': 'blog/2018/01/09/blog-workflow/index.md'
        '2018/03/24/vdi-and-containers.md': 'blog/2018/03/24/vdi-and-containers/index.md'
        '2018/02/04/graphviz-sh-zsh-bash-refactor.md': 'blog/2018/02/04/graphviz-sh-zsh-bash-refactor/index.md'
        '2018/02/10/hardware-touchpad-troubles.md': 'blog/2018/02/10/hardware-touchpad-troubles/index.md'
        '2018/02/13/asset-regeneration-script.md': 'blog/2018/02/13/asset-regeneration-script/index.md'
        '2018/02/11/color-safe-palette.md': 'blog/2018/02/11/color-safe-palette/index.md'
        '2018/02/26/graphviz-dot-basics-pt-1.md': 'blog/2018/02/26/graphviz-dot-basics-pt-1/index.md'
        '2018/02/27/graphviz-dot-basics-pt-2.md': 'blog/2018/02/27/graphviz-dot-basics-pt-2/index.md'
        '2018/02/18/link-rollup.md': 'blog/2018/02/18/link-rollup/index.md'
        '2022/08/31/mike-writes.md': 'blog/2022/08/31/mike-writes/index.md'
        '2022/08/31/mike-reads.md': 'blog/2022/08/31/mike-reads/index.md'
        '2022/09/01/phoenix-guards-pt-1.md': 'blog/2022/09/01/phoenix-guards-pt-1/index.md'
  - mkdocs-simple-hooks:
      hooks:
        on_pre_build: "hooks:on_pre_build"

# Navigation Structure
nav:
  - Home: index.md
  - Blog: blog/index.md
